# Generated by Django 4.2.16 on 2024-10-14 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('plot', models.TextField()),
                ('poster', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True, null=True)),
                ('isReleased', models.BooleanField(default=False)),
                ('isSeries', models.BooleanField(default=False)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)])),
                ('productionStatus', models.CharField(blank=True, max_length=100, null=True)),
                ('contentRating', models.CharField(blank=True, max_length=10, null=True)),
                ('contentType', models.CharField(blank=True, max_length=50, null=True)),
                ('runtime', models.CharField(blank=True, max_length=20, null=True)),
                ('runtimeSeconds', models.PositiveIntegerField(blank=True, null=True)),
                ('releaseDetailed', models.JSONField(blank=True, null=True)),
                ('releaseDate', models.DateField(blank=True, null=True)),
                ('rating', models.JSONField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('reviews', models.JSONField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, null=True)),
                ('spokenLanguages', models.JSONField(blank=True, null=True)),
                ('filmingLocations', models.JSONField(blank=True, null=True)),
                ('actors', models.JSONField(blank=True, null=True)),
                ('actors_v2', models.JSONField(blank=True, null=True)),
                ('directors', models.JSONField(blank=True, null=True)),
                ('directors_v2', models.JSONField(blank=True, null=True)),
                ('writers', models.JSONField(blank=True, null=True)),
                ('writers_v2', models.JSONField(blank=True, null=True)),
                ('creators', models.JSONField(blank=True, null=True)),
                ('creators_v2', models.JSONField(blank=True, null=True)),
                ('top_credits', models.JSONField(blank=True, null=True)),
                ('genre', models.JSONField(blank=True, null=True)),
                ('award', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sguser',
            name='favourites',
            field=models.ManyToManyField(related_name='favourites', to='base.movie'),
        ),
    ]
