# Generated by Django 4.2.16 on 2024-10-14 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_movie_sguser_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sguser',
            name='favourites',
        ),
        migrations.AddField(
            model_name='movie',
            name='lovers',
            field=models.ManyToManyField(blank=True, related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
