# Generated by Django 4.2.16 on 2024-10-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_sguser_favourites_movie_lovers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='lovers',
        ),
        migrations.AddField(
            model_name='sguser',
            name='lovers',
            field=models.ManyToManyField(blank=True, related_name='favourites', to='base.movie'),
        ),
    ]
