# Generated by Django 4.2.16 on 2024-10-14 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_movie_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sguser',
            old_name='lovers',
            new_name='favourites',
        ),
    ]
