# Generated by Django 4.2.16 on 2024-10-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_lovers_sguser_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='sguser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
