# Generated by Django 4.2.16 on 2024-10-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_sguser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sguser',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
