# Generated by Django 4.2.16 on 2024-10-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_sguser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='stream',
            field=models.URLField(blank=True, null=True),
        ),
    ]
