# Generated by Django 4.2.16 on 2024-10-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_movie_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='captions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
