# Generated by Django 4.2.16 on 2024-10-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='telegram_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
