# Generated by Django 4.2.16 on 2024-10-22 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_admin_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
