# Generated by Django 4.2.16 on 2024-10-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_delete_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='sguser',
            name='telegram_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
